"""
Intelligence Reports System for Merrywinter Security Consulting
Classified intel sharing with clearance-based access - SLASH COMMANDS ONLY
"""

import discord
from discord.ext import commands
from discord import app_commands
from datetime import datetime, timedelta
import random
import json

from config.settings import Config
from utils.helpers import get_user_clearance, create_embed
from utils.storage import Storage

class IntelligenceSystem(commands.Cog):
    """Intelligence reports and threat assessment system"""

    def __init__(self, bot):
        self.bot = bot
        self.storage = Storage()

    async def interaction_check(self, interaction: discord.Interaction) -> bool:
        """Check if interaction is in authorized guild"""
        return Config.check_guild_authorization(interaction.guild.id)

    @app_commands.command(name="intel_report", description="Generate intelligence report (BETA+ clearance)")
    @app_commands.describe(
        report_type="Type of intelligence report",
        classification="Classification level of the report",
        sector="Sector for intelligence gathering"
    )
    @app_commands.choices(
        report_type=[
            app_commands.Choice(name="Threat Assessment", value="threat"),
            app_commands.Choice(name="Sector Analysis", value="sector"),
            app_commands.Choice(name="Enemy Movement", value="movement"),
            app_commands.Choice(name="Resource Intelligence", value="resource"),
            app_commands.Choice(name="Communication Intercept", value="comms"),
            app_commands.Choice(name="Tactical Overview", value="tactical")
        ],
        classification=[
            app_commands.Choice(name="Confidential", value="confidential"),
            app_commands.Choice(name="Secret", value="secret"),
            app_commands.Choice(name="Top Secret", value="top_secret")
        ],
        sector=[
            app_commands.Choice(name="Alpha - Urban", value="alpha"),
            app_commands.Choice(name="Beta - Desert", value="beta"),
            app_commands.Choice(name="Gamma - Naval", value="gamma"),
            app_commands.Choice(name="Delta - Mountain", value="delta"),
            app_commands.Choice(name="Epsilon - Jungle", value="epsilon"),
            app_commands.Choice(name="Zeta - Arctic", value="zeta")
        ]
    )
    async def intel_report(self, interaction: discord.Interaction, report_type: str, classification: str, sector: str = None):
        """Generate intelligence report"""
        user_clearance = get_user_clearance(interaction.user.roles)

        # Check if user has BETA+ clearance
        if not Config.has_permission(user_clearance, 'BETA_SECURITY'):
            await interaction.response.send_message("❌ You need BETA+ clearance to access intelligence reports.", ephemeral=True)
            return

        # Check classification access
        classification_requirements = {
            'confidential': 'BETA_SECURITY',
            'secret': 'BETA_SECURITY', 
            'top_secret': 'EXECUTIVE_COMMAND'
        }

        required_clearance = classification_requirements.get(classification, 'BETA_SECURITY')
        if not Config.has_permission(user_clearance, required_clearance):
            await interaction.response.send_message(f"❌ You need {required_clearance.replace('_', ' ').title()} clearance for {classification.replace('_', ' ').title()} reports.", ephemeral=True)
            return

        # Generate report ID
        report_id = f"INTEL-{random.randint(100000, 999999)}"

        # Generate report content based on type
        report_content = self._generate_intel_content(report_type, sector)

        # Create classification colors
        classification_colors = {
            'confidential': 0x0066CC,  # Blue
            'secret': 0xFF6600,       # Orange
            'top_secret': 0xFF0000    # Red
        }

        # Handle classification display
        if classification == 'top_secret':
            classification_display = "🔴 TOP SECRET"
            access_note = "Executive Command Only"
        elif classification == 'secret':
            classification_display = "🟡 SECRET"
            access_note = "BETA+ Clearance Required"
        else:
            classification_display = "🔵 CONFIDENTIAL"
            access_note = "BETA+ Clearance Required"

        # Create intelligence embed
        embed = discord.Embed(
            title=f"📊 INTELLIGENCE REPORT - {classification_display}",
            description=f"**Report ID:** {report_id}\n"
                       f"**Generated By:** {interaction.user.display_name}\n"
                       f"**Clearance Level:** {user_clearance}\n"
                       f"**Access Level:** {access_note}\n"
                       f"**Timestamp:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC",
            color=classification_colors.get(classification, 0x0066CC)
        )

        embed.add_field(
            name="📋 Report Details",
            value=f"**Type:** {report_content['type']}\n"
                  f"**Sector:** {report_content['sector']}\n"
                  f"**Priority:** {report_content['priority']}\n"
                  f"**Reliability:** {report_content['reliability']}",
            inline=False
        )

        embed.add_field(
            name="🔍 Intelligence Summary",
            value=report_content['summary'],
            inline=False
        )

        embed.add_field(
            name="⚠️ Threat Assessment",
            value=report_content['threat_level'],
            inline=False
        )

        embed.add_field(
            name="📌 Recommendations",
            value=report_content['recommendations'],
            inline=False
        )

        embed.set_footer(text=f"{Config.COMPANY_NAME} - Intelligence Division")

        # Save intelligence report
        intel_data = {
            'report_id': report_id,
            'type': report_type,
            'classification': classification,
            'sector': sector,
            'generated_by': interaction.user.id,
            'content': report_content,
            'timestamp': datetime.utcnow().isoformat(),
            'guild_id': interaction.guild.id
        }

        await self.storage.save_intel_report(intel_data)

        # Send report (ephemeral for classified content)
        is_ephemeral = classification in ['secret', 'top_secret']
        await interaction.response.send_message(embed=embed, ephemeral=is_ephemeral)

    def _generate_intel_content(self, report_type: str, sector: str) -> dict:
        """Generate intelligence report content"""

        sector_names = {
            'alpha': 'Alpha - Urban Operations',
            'beta': 'Beta - Desert Warfare',
            'gamma': 'Gamma - Naval Operations',
            'delta': 'Delta - Mountain Warfare',
            'epsilon': 'Epsilon - Jungle Operations',
            'zeta': 'Zeta - Arctic Operations'
        }

        threat_levels = ["LOW", "MODERATE", "HIGH", "CRITICAL"]
        priorities = ["LOW", "MEDIUM", "HIGH", "URGENT"]
        reliability_levels = ["C - Fairly Reliable", "B - Usually Reliable", "A - Completely Reliable"]

        content_templates = {
            'threat': {
                'type': 'Threat Assessment Report',
                'summary': f"Analysis of potential threats in operational area. {random.choice(['Enemy activity detected', 'Unusual communications intercepted', 'Suspicious movement patterns identified', 'Resource accumulation observed'])}. Recommend enhanced surveillance protocols.",
                'threat_level': f"**Current Threat Level:** {random.choice(threat_levels)}\n• {random.choice(['Hostile forces', 'Unknown contacts', 'Potential infiltration', 'Equipment anomalies'])} reported\n• {random.choice(['Increased patrols', 'Enhanced security', 'Additional reconnaissance', 'Defensive preparations'])} recommended",
                'recommendations': f"• {random.choice(['Deploy additional surveillance', 'Increase patrol frequency', 'Enhance perimeter security', 'Coordinate with allied forces'])}\n• {random.choice(['Monitor communications', 'Establish checkpoints', 'Prepare contingency plans', 'Brief all personnel'])}\n• {random.choice(['Review security protocols', 'Update threat assessments', 'Coordinate with intelligence', 'Maintain high alert status'])}"
            },
            'sector': {
                'type': 'Sector Analysis Report',
                'summary': f"Comprehensive analysis of sector conditions and strategic value. {random.choice(['Infrastructure assessment complete', 'Resource evaluation conducted', 'Population analysis finished', 'Strategic value determined'])}. Key findings documented.",
                'threat_level': f"**Sector Status:** {random.choice(['SECURE', 'CONTESTED', 'HOSTILE', 'UNKNOWN'])}\n• {random.choice(['Civilian population', 'Military presence', 'Infrastructure status', 'Resource availability'])} assessed\n• {random.choice(['Strategic importance', 'Tactical advantages', 'Defensive capabilities', 'Logistical considerations'])} evaluated",
                'recommendations': f"• {random.choice(['Establish forward operating base', 'Secure supply lines', 'Coordinate with locals', 'Deploy specialized units'])}\n• {random.choice(['Monitor border activity', 'Assess infrastructure needs', 'Evaluate resource requirements', 'Plan contingencies'])}\n• {random.choice(['Maintain sector control', 'Prepare for operations', 'Coordinate with allies', 'Update intelligence files'])}"
            },
            'movement': {
                'type': 'Enemy Movement Report',
                'summary': f"Tracking and analysis of hostile force movements. {random.choice(['Large convoy spotted', 'Troop concentrations identified', 'Equipment transfers observed', 'Unusual activity patterns detected'])}. Movement patterns analyzed.",
                'threat_level': f"**Movement Assessment:** {random.choice(['ACTIVE', 'INCREASING', 'DECREASING', 'STATIC'])}\n• {random.choice(['Vehicle movements', 'Personnel transfers', 'Equipment deployment', 'Supply convoys'])} tracked\n• {random.choice(['Destination analysis', 'Route assessment', 'Timing evaluation', 'Intent determination'])} completed",
                'recommendations': f"• {random.choice(['Intercept communications', 'Deploy observation posts', 'Coordinate air reconnaissance', 'Prepare response forces'])}\n• {random.choice(['Track convoy routes', 'Monitor checkpoints', 'Assess capabilities', 'Predict intentions'])}\n• {random.choice(['Prepare countermeasures', 'Alert allied forces', 'Update movement logs', 'Maintain surveillance'])}"
            },
            'resource': {
                'type': 'Resource Intelligence Report',
                'summary': f"Assessment of available resources and supply chain analysis. {random.choice(['Supply depot identified', 'Resource shortages detected', 'Stockpile locations mapped', 'Distribution networks analyzed'])}. Resource availability evaluated.",
                'threat_level': f"**Resource Status:** {random.choice(['ADEQUATE', 'LIMITED', 'CRITICAL', 'ABUNDANT'])}\n• {random.choice(['Ammunition supplies', 'Medical resources', 'Food provisions', 'Fuel availability'])} assessed\n• {random.choice(['Supply chain security', 'Distribution efficiency', 'Storage capacity', 'Resupply schedules'])} evaluated",
                'recommendations': f"• {random.choice(['Secure supply lines', 'Establish resource caches', 'Coordinate resupply', 'Monitor consumption'])}\n• {random.choice(['Assess alternative sources', 'Prepare contingency supplies', 'Optimize distribution', 'Reduce waste'])}\n• {random.choice(['Maintain inventory logs', 'Coordinate with logistics', 'Plan resource allocation', 'Monitor supply security'])}"
            },
            'comms': {
                'type': 'Communication Intercept Report',
                'summary': f"Analysis of intercepted communications and signals intelligence. {random.choice(['Encrypted transmissions decoded', 'Communication patterns identified', 'Signal sources located', 'Message content analyzed'])}. Intelligence value assessed.",
                'threat_level': f"**Communication Assessment:** {random.choice(['HIGH VALUE', 'MEDIUM VALUE', 'LOW VALUE', 'INCONCLUSIVE'])}\n• {random.choice(['Command communications', 'Tactical frequencies', 'Logistics coordination', 'Intelligence chatter'])} intercepted\n• {random.choice(['Encryption methods', 'Communication protocols', 'Network topology', 'Signal sources'])} analyzed",
                'recommendations': f"• {random.choice(['Continue monitoring', 'Expand intercept coverage', 'Decode additional traffic', 'Identify key personnel'])}\n• {random.choice(['Analyze communication patterns', 'Track frequency usage', 'Map network structure', 'Assess security measures'])}\n• {random.choice(['Coordinate with signals intelligence', 'Update intercept priorities', 'Maintain operational security', 'Brief command staff'])}"
            },
            'tactical': {
                'type': 'Tactical Overview Report',
                'summary': f"Comprehensive tactical situation assessment and operational planning. {random.choice(['Battlefield conditions analyzed', 'Enemy capabilities assessed', 'Friendly force status evaluated', 'Tactical opportunities identified'])}. Strategic recommendations prepared.",
                'threat_level': f"**Tactical Status:** {random.choice(['FAVORABLE', 'NEUTRAL', 'UNFAVORABLE', 'CRITICAL'])}\n• {random.choice(['Force ratios', 'Terrain advantages', 'Weather conditions', 'Equipment status'])} evaluated\n• {random.choice(['Operational readiness', 'Strategic positioning', 'Tactical mobility', 'Support availability'])} assessed",
                'recommendations': f"• {random.choice(['Exploit tactical advantages', 'Reinforce key positions', 'Coordinate support elements', 'Prepare offensive operations'])}\n• {random.choice(['Assess enemy weaknesses', 'Identify strategic objectives', 'Plan tactical maneuvers', 'Coordinate with allies'])}\n• {random.choice(['Maintain tactical flexibility', 'Prepare contingency plans', 'Monitor situation changes', 'Update operational orders'])}"
            }
        }

        template = content_templates.get(report_type, content_templates['threat'])

        return {
            'type': template['type'],
            'sector': sector_names.get(sector, 'Multiple Sectors') if sector else 'All Sectors',
            'priority': random.choice(priorities),
            'reliability': random.choice(reliability_levels),
            'summary': template['summary'],
            'threat_level': template['threat_level'],
            'recommendations': template['recommendations']
        }

    @app_commands.command(name="intel_briefing", description="Request intelligence briefing (BETA+ clearance)")
    @app_commands.describe(
        briefing_type="Type of intelligence briefing requested"
    )
    @app_commands.choices(
        briefing_type=[
            app_commands.Choice(name="Daily Intelligence Summary", value="daily"),
            app_commands.Choice(name="Weekly Threat Assessment", value="weekly"),
            app_commands.Choice(name="Mission-Specific Brief", value="mission"),
            app_commands.Choice(name="Strategic Intelligence Overview", value="strategic"),
            app_commands.Choice(name="Emergency Threat Update", value="emergency")
        ]
    )
    async def intel_briefing(self, interaction: discord.Interaction, briefing_type: str):
        """Request intelligence briefing"""
        user_clearance = get_user_clearance(interaction.user.roles)

        # Check if user has BETA+ clearance
        if not Config.has_permission(user_clearance, 'BETA_SECURITY'):
            await interaction.response.send_message("❌ You need BETA+ clearance to request intelligence briefings.", ephemeral=True)
            return

        # Generate briefing ID
        briefing_id = f"BRIEF-{random.randint(10000, 99999)}"

        # Generate briefing content
        briefing_content = self._generate_briefing_content(briefing_type)

        # Create briefing embed
        embed = discord.Embed(
            title=f"📊 INTELLIGENCE BRIEFING - {briefing_content['title']}",
            description=f"**Briefing ID:** {briefing_id}\n"
                       f"**Requested By:** {interaction.user.display_name}\n"
                       f"**Clearance Level:** {user_clearance}\n"
                       f"**Classification:** {briefing_content['classification']}\n"
                       f"**Timestamp:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC",
            color=0x00FF00
        )

        embed.add_field(
            name="📋 Briefing Summary",
            value=briefing_content['summary'],
            inline=False
        )

        embed.add_field(
            name="🎯 Key Points",
            value=briefing_content['key_points'],
            inline=False
        )

        embed.add_field(
            name="📌 Action Items",
            value=briefing_content['action_items'],
            inline=False
        )

        embed.set_footer(text=f"{Config.COMPANY_NAME} - Intelligence Division")

        # Save briefing data
        briefing_data = {
            'briefing_id': briefing_id,
            'type': briefing_type,
            'requested_by': interaction.user.id,
            'content': briefing_content,
            'timestamp': datetime.utcnow().isoformat(),
            'guild_id': interaction.guild.id
        }

        await self.storage.save_intel_briefing(briefing_data)

        await interaction.response.send_message(embed=embed, ephemeral=True)

    def _generate_briefing_content(self, briefing_type: str) -> dict:
        """Generate intelligence briefing content"""

        briefing_templates = {
            'daily': {
                'title': 'DAILY INTELLIGENCE SUMMARY',
                'classification': 'CONFIDENTIAL',
                'summary': f"Daily intelligence summary for {datetime.utcnow().strftime('%Y-%m-%d')}. Overall threat level remains {random.choice(['LOW', 'MODERATE', 'ELEVATED'])}. No immediate threats to personnel or operations identified.",
                'key_points': f"• {random.choice(['Sector Alpha', 'Sector Beta', 'Sector Gamma'])} reports normal activity levels\n• {random.choice(['Communication intercepts', 'Surveillance reports', 'Patrol updates'])} indicate stable conditions\n• {random.choice(['Weather conditions', 'Supply status', 'Personnel readiness'])} remain optimal for operations",
                'action_items': f"• Continue routine surveillance protocols\n• Maintain standard alert levels\n• Update intelligence files as needed\n• Prepare for tomorrow's briefing cycle"
            },
            'weekly': {
                'title': 'WEEKLY THREAT ASSESSMENT',
                'classification': 'SECRET',
                'summary': f"Weekly threat assessment covering {(datetime.utcnow() - timedelta(days=7)).strftime('%Y-%m-%d')} to {datetime.utcnow().strftime('%Y-%m-%d')}. Threat patterns analyzed and risk factors evaluated.",
                'key_points': f"• {random.choice(['Increased activity', 'Decreased activity', 'Stable patterns'])} observed in multiple sectors\n• {random.choice(['New threats identified', 'Existing threats monitored', 'Threat levels reassessed'])}\n• {random.choice(['Intelligence gaps', 'Data correlation', 'Pattern analysis'])} completed",
                'action_items': f"• Review security protocols based on threat assessment\n• Adjust patrol schedules and coverage areas\n• Coordinate with allied intelligence services\n• Prepare next week's intelligence priorities"
            },
            'mission': {
                'title': 'MISSION-SPECIFIC INTELLIGENCE BRIEF',
                'classification': 'SECRET',
                'summary': f"Mission-specific intelligence brief prepared for upcoming operations. Target area analysis completed with {random.choice(['favorable', 'challenging', 'complex'])} operational conditions identified.",
                'key_points': f"• Target area: {random.choice(['Secured', 'Contested', 'Hostile'])} with {random.choice(['light', 'moderate', 'heavy'])} opposition expected\n• Environmental factors: {random.choice(['Favorable', 'Challenging', 'Adverse'])} conditions predicted\n• Support assets: {random.choice(['Available', 'Limited', 'Coordinated'])} for mission timeframe",
                'action_items': f"• Brief all mission personnel on intelligence findings\n• Coordinate with support elements\n• Prepare contingency plans for identified risks\n• Establish communication protocols for mission updates"
            },
            'strategic': {
                'title': 'STRATEGIC INTELLIGENCE OVERVIEW',
                'classification': 'SECRET',
                'summary': f"Strategic intelligence overview focusing on long-term trends and regional stability. Analysis covers {random.choice(['30-day', '60-day', '90-day'])} outlook with strategic implications assessed.",
                'key_points': f"• Regional stability: {random.choice(['Improving', 'Stable', 'Deteriorating'])} based on multiple indicators\n• Strategic threats: {random.choice(['Emerging', 'Persistent', 'Diminishing'])} challenges identified\n• Resource allocation: {random.choice(['Optimized', 'Adjusted', 'Realigned'])} based on strategic priorities",
                'action_items': f"• Update strategic planning documents\n• Coordinate with strategic partners\n• Assess resource requirements for strategic objectives\n• Prepare strategic recommendations for leadership"
            },
            'emergency': {
                'title': 'EMERGENCY THREAT UPDATE',
                'classification': 'URGENT',
                'summary': f"Emergency threat update issued at {datetime.utcnow().strftime('%H:%M:%S')} UTC. Immediate threat assessment indicates {random.choice(['elevated', 'high', 'critical'])} risk level requiring immediate attention.",
                'key_points': f"• Immediate threat: {random.choice(['Hostile activity', 'Security breach', 'Equipment failure'])} detected\n• Impact assessment: {random.choice(['Local', 'Regional', 'Widespread'])} effects possible\n• Response status: {random.choice(['Initiated', 'Coordinated', 'Escalated'])} emergency protocols",
                'action_items': f"• Implement immediate security measures\n• Alert all relevant personnel\n• Coordinate emergency response\n• Provide regular updates to command staff"
            }
        }

        return briefing_templates.get(briefing_type, briefing_templates['daily'])

    @app_commands.command(name="intel_search", description="Search intelligence database (BETA+ clearance)")
    @app_commands.describe(
        search_term="Search term for intelligence database",
        classification="Maximum classification level to search"
    )
    @app_commands.choices(
        classification=[
            app_commands.Choice(name="Confidential", value="confidential"),
            app_commands.Choice(name="Secret", value="secret"),
            app_commands.Choice(name="Top Secret", value="top_secret")
        ]
    )
    async def intel_search(self, interaction: discord.Interaction, search_term: str, classification: str = "confidential"):
        """Search intelligence database"""
        user_clearance = get_user_clearance(interaction.user.roles)

        # Check if user has BETA+ clearance
        if not Config.has_permission(user_clearance, 'BETA_SECURITY'):
            await interaction.response.send_message("❌ You need BETA+ clearance to search intelligence database.", ephemeral=True)
            return

        # Check classification access
        classification_requirements = {
            'confidential': 'BETA_SECURITY',
            'secret': 'BETA_SECURITY',
            'top_secret': 'EXECUTIVE_COMMAND'
        }

        required_clearance = classification_requirements.get(classification, 'BETA_SECURITY')
        if not Config.has_permission(user_clearance, required_clearance):
            await interaction.response.send_message(f"❌ You need {required_clearance.replace('_', ' ').title()} clearance to search {classification.replace('_', ' ').title()} files.", ephemeral=True)
            return

        # Generate search results
        results = self._generate_search_results(search_term, classification)

        # Create search results embed
        embed = discord.Embed(
            title=f"🔍 INTELLIGENCE DATABASE SEARCH",
            description=f"**Search Term:** {search_term}\n"
                       f"**Classification Level:** {classification.replace('_', ' ').title()}\n"
                       f"**Searched By:** {interaction.user.display_name}\n"
                       f"**Results Found:** {len(results)}\n"
                       f"**Timestamp:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC",
            color=0x9932CC
        )

        if results:
            for i, result in enumerate(results[:5], 1):  # Limit to 5 results
                embed.add_field(
                    name=f"📄 Result {i}: {result['title']}",
                    value=f"**ID:** {result['id']}\n"
                          f"**Date:** {result['date']}\n"
                          f"**Summary:** {result['summary']}\n"
                          f"**Classification:** {result['classification']}",
                    inline=False
                )
        else:
            embed.add_field(
                name="❌ No Results Found",
                value="No matching intelligence records found in the database.",
                inline=False
            )

        embed.set_footer(text=f"{Config.COMPANY_NAME} - Intelligence Database")

        await interaction.response.send_message(embed=embed, ephemeral=True)

    def _generate_search_results(self, search_term: str, classification: str) -> list:
        """Generate mock search results"""

        # Generate 2-4 mock results
        num_results = random.randint(2, 4)
        results = []

        for i in range(num_results):
            result = {
                'id': f"INTEL-{random.randint(100000, 999999)}",
                'title': f"{random.choice(['Threat Report', 'Sector Analysis', 'Movement Intel', 'Resource Assessment'])} - {search_term}",
                'date': (datetime.utcnow() - timedelta(days=random.randint(1, 30))).strftime('%Y-%m-%d'),
                'summary': f"Intelligence report containing information related to {search_term}. {random.choice(['High priority', 'Medium priority', 'Low priority'])} intelligence with {random.choice(['verified', 'unverified', 'partial'])} information.",
                'classification': classification.replace('_', ' ').title()
            }
            results.append(result)

        return results

async def setup(bot):
    """Setup function for the cog"""
    await bot.add_cog(IntelligenceSystem(bot))